name: Pat Xu
description: Blogging about stuffs
meta_description: "Pat Xu"

markdown: kramdown
highlighter: rogue
logo: false
paginate: 15
baseurl: 
domain_name: 'http://patrickxu.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'patrickxu.com'
author:         'Pat Xu'
