name: Pat Xu
description: "Under Development"
meta_description: "Personal website by Pat Xu"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'http://patrickxu.com'
google_analytics: 'UA-78993479-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'patrickxu.com'
author:         'Pat Xu'
